---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, LICENSE.txt, README.md, .gitignore]
permalink: / ## disables post output
timezone: null
lsi: false
markdown: kramdown
highlighter: pygments


### content configuration ###
title:       "Les conférences MiNET"
keywords:    "conference, MiNET, openstack, git, debian, cybersecurite, doocracy"
description: "Conférences annuelles sur le monde du logiciel libre, organisées par l'association MiNET."
favicon:     "img/favicon.ico"
piwik_site_id: "12"


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
  gray:      '#1C1C1C'
